
import { ReportItem } from './types';

export const ALL_REPORTS: ReportItem[] = [
  // ==========================================
  // 9. BRANDING & SEMIÓTICA DE MARCA (COMPLETO)
  // ==========================================
  {
    id: 'B.1',
    cat: 'brand',
    title: '9.1 Atlas Semiótico de Marcas',
    desc: 'Territórios de significação no Brasil.',
    summary: 'Mapeamento de arquétipos e territórios de significado em 12 setores da economia brasileira.',
    methodology: 'Análise semiótica estruturalista cruzada com Big Data de campanhas 2020-2026.',
    analysis: 'O território de marcas no Brasil vive uma síncrese entre a tradição local e a aspiração global. Marcas que ativam o arquétipo do "Criador" apresentam 40% mais Brand Equity em tecnologia do que as que ainda usam o "Herói". O Atlas identifica o "Localismo Afetivo" como o território mais fértil para 2026.',
    findings: ['Arquétipo Criador domina tech (+40%)', 'Tensão Local vs Global gera fricção', 'Saturação do Herói em 75% dos setores'],
    recommendations: 'Ocupar territórios de "Mago" para fugir da guerra de preços commoditizada.',
    nextSteps: 'Auditoria de tom de voz para micro-segmentos geracionais.',
    references: ['Roland Barthes: Mitologias', 'Douglas Holt: Cultural Strategy'],
    sources: [{ label: 'Semiotics Hub', url: 'https://semioticsforbranding.com' }],
    truthScore: 98.2,
    metrics: [{ label: 'Cultural Relevance', value: '9.2/10', percentage: 92, trend: 'up' }],
    insightCards: [{ title: 'Síncrese Semiótica', content: 'Marcas vencedoras fundem o "Craft Local" com a "Precisão Global".' }]
  },
  {
    id: 'B.2',
    cat: 'brand',
    title: '9.2 Percepção Multidimensional',
    desc: 'Gaps de identidade e mapas perceptuais.',
    summary: 'Análise multidimensional das dimensões de status, inovação e sustentabilidade.',
    methodology: 'Word association tests e mapas de calor de elasticidade semântica.',
    analysis: '40% das marcas Premium no Brasil sofrem de diluição ao tentarem democratizar o acesso. O gap entre a identidade projetada (ESG) e a imagem percebida (Greenwashing) é o maior risco reputacional de 2026.',
    findings: ['Gap Identidade-Imagem: 22%', 'Elasticidade Semântica limitada em luxo'],
    recommendations: 'Reduzir a amplitude de extensão de marca para preservar o core semântico.',
    nextSteps: 'Rebranding focado em consistência de sinais táteis.',
    references: ['Kapferer: Brand Identity Prism'],
    truthScore: 96.5
  },
  {
    id: 'B.3',
    cat: 'brand',
    title: '9.3 Semiótica Visual: Transformação',
    desc: 'Identidades visuais 2020-2026.',
    summary: 'A oscilação entre Flat Design e o novo "Maximalismo Orgânico".',
    methodology: 'Análise computacional de paletas e tipografia em 1.000 redesigns.',
    analysis: 'O minimalismo extremo saturou. Marcas agora usam "Texturas de Autenticidade" e serifas pesadas para sinalizar humanidade frente à IA. A tipografia tornou-se o principal manifestante de personalidade.',
    findings: ['Retorno das Serifas: +30%', 'Maximalismo como distinção visual'],
    recommendations: 'Adotar elementos visuais imperfeitos (Craft) para sinalizar valor humano.',
    nextSteps: 'Update de Design Systems para layouts não-lineares.',
    references: ['Typography as Identity 2026'],
    truthScore: 97.8
  },
  {
    id: 'B.4',
    cat: 'brand',
    title: '9.4 Narrativas e Storytelling',
    desc: 'Estruturas de convencimento emocional.',
    summary: 'Análise de coerência narrativa e autenticidade percebida vs construída.',
    methodology: 'Análise estrutural de jornadas narrativas cross-media.',
    analysis: 'O Purpose-driven branding morreu por falta de sinceridade. O novo paradigma é o "Radical Transparency", onde o processo de produção é a própria história.',
    findings: ['Storyliving > Storytelling', 'Radical Transparency: +88% confiança'],
    recommendations: 'Substituir manifestos genéricos por documentação de processos reais.',
    nextSteps: 'Estratégia de Transmedia Storytelling para avatares de IA.',
    references: ['Joseph Campbell: Hero of a Thousand Faces'],
    truthScore: 95.1
  },
  {
    id: 'B.5',
    cat: 'brand',
    title: '9.5 Sonic Branding e Identidade',
    desc: 'Territórios emocionais sonoros.',
    summary: 'Memorabilidade de audio logos e playlists branded.',
    methodology: 'Testes de retenção de marca em ambientes audio-only.',
    analysis: 'Em dispositivos sem tela, o som é a única marca. O silêncio estratégico está sendo usado como signo de luxo em apps de meditação e finanças de alta renda.',
    findings: ['Memorabilidade de Áudio: +45%', 'Identidade Vocal é o novo Logo'],
    recommendations: 'Desenvolver dicionário sonoro proprietário antes de investir em campanhas.',
    nextSteps: 'Criação de audio logo em 8D para ambientes imersivos.',
    references: ['Oxford: Sound & Memory 2026'],
    truthScore: 95.8
  },
  {
    id: 'B.6',
    cat: 'brand',
    title: '9.6 Semântica do Consumo',
    desc: 'Linguagem e Naming.',
    summary: 'Como o vocabulário de marca molda o posicionamento de mercado.',
    methodology: 'Análise linguística de taglines e glossários proprietários.',
    analysis: 'Regionalismos sofisticados estão vencendo estrangeirismos genéricos. Criar uma "Linguagem Própria" isola a marca da comparação direta de preços.',
    findings: ['Regionalismo Sofisticado: Tendência #1', 'Neologismos como barreira de entrada'],
    recommendations: 'Arquitetar um glossário de termos exclusivos para a categoria.',
    nextSteps: 'Treinamento de LLMs de suporte no tom de voz regional.',
    references: ['Saussure: Curso de Linguística Geral'],
    truthScore: 94.4
  },
  {
    id: 'B.7',
    cat: 'brand',
    title: '9.7 Mitologias Contemporâneas',
    desc: 'Marcas como sistemas de crença.',
    summary: 'Rituais de consumo e objetos totêmicos na era digital.',
    methodology: 'Observação etnográfica de comunidades e rituais de unboxing.',
    analysis: 'Marcas operam como religiões seculares. O "Ritual de Ativação" digital confere o status de pertencimento à tribo.',
    findings: ['Rituais de Posse: Chave para retenção', 'Objetos Totêmicos digitais (NFTs/Skins)'],
    recommendations: 'Desenhar rituais de fidelidade que exijam esforço simbólico do consumidor.',
    nextSteps: 'Estratégia de rituais para marcas D2C.',
    references: ['Mircea Eliade: O Sagrado e o Profano'],
    truthScore: 93.7
  },
  {
    id: 'B.8',
    cat: 'brand',
    title: '9.8 Semiótica de Packaging',
    desc: 'Materialidade e Unboxing.',
    summary: 'Formas e texturas que comunicam sustentabilidade e status.',
    methodology: 'Análise sensorial e testes de Shelf Impact.',
    analysis: 'O luxo é tátil. Embalagens "Single-Material" comunicam mais inteligência que design gráfico complexo. O Unboxing tornou-se o momento central da jornada semiótica.',
    findings: ['Textura comunica Sustentabilidade', 'Fim do plástico como signo de modernidade'],
    recommendations: 'Eliminar camadas extras em favor de materiais de alta densidade sensorial.',
    nextSteps: 'Prototipagem de embalagens compostáveis de luxo.',
    references: ['Packaging Semiotics 2026'],
    truthScore: 98.1
  },
  {
    id: 'B.9',
    cat: 'brand',
    title: '9.9 Branding Geracional',
    desc: 'Códigos por faixa etária.',
    summary: 'Fluidez da Gen Alpha vs Autenticidade da Gen Z.',
    methodology: 'Mapeamento de tendências geracionais e consumo de mídia.',
    analysis: 'A Gen Alpha exige Phygital Gamification. Marcas que não possuem uma camada lúdica e interativa são invisíveis para os consumidores de 2026.',
    findings: ['Gen Alpha: 100% Phygital', 'Gen Z: Desejo de "Low-Tech" como luxo'],
    recommendations: 'Criar sub-brands com códigos semióticos divergentes por idade.',
    nextSteps: 'Estratégia de gamificação para marcas de varejo.',
    references: ['McKinsey: Gen Z Report'],
    truthScore: 96.9
  },
  {
    id: 'B.10',
    cat: 'brand',
    title: '9.10 Luxo vs Premium vs Mass',
    desc: 'Quiet Luxury vs Logomania.',
    summary: 'Códigos distintivos de raridade e democratização.',
    methodology: 'Análise de precificação e densidade de logos.',
    analysis: 'O Quiet Luxury domina os centros urbanos, enquanto a Logomania cíclica retorna como sinal de ascensão em mercados emergentes.',
    findings: ['Quiet Luxury: Maturidade em SP', 'Logomania: Ascensão regional'],
    recommendations: 'Utilizar signos discretos para produtos core e logos para produtos de entrada.',
    nextSteps: 'Curadoria de canais seletivos via Drex.',
    references: ['The Luxury Strategy: Kapferer'],
    truthScore: 97.2
  },
  {
    id: 'B.11',
    cat: 'brand',
    title: '9.11 Movimentos Culturais',
    desc: 'Ativismo e Apropriação.',
    summary: 'Riscos semióticos de marcas que surfam tendências sociais.',
    methodology: 'Análise de sentimento e tracking de consistência histórica.',
    analysis: 'Marcas "Causistas" sem base histórica sofrem rejeição imediata. O ativismo silencioso (nas operações) é mais valorizado que o barulhento (nas campanhas).',
    findings: ['Risco de Rejeição: 65% em marcas inconsistentes', 'Sinceridade Semiótica'],
    recommendations: 'Comunicar ativismo apenas após 12 meses de mudanças operacionais comprovadas.',
    nextSteps: 'Auditoria de diversidade e sustentabilidade interna.',
    references: ['Douglas Holt: How Brands Become Icons'],
    truthScore: 94.8
  },
  {
    id: 'B.12',
    cat: 'brand',
    title: '9.12 Dashboard: Saúde Semiótica',
    desc: 'Métricas de Coerência.',
    summary: 'Framework para medição de densidade semântica e vulnerabilidade.',
    methodology: 'Criação de índices proprietários via NLP e redes neurais.',
    analysis: 'Propomos o ISS (Índice de Saúde Semiótica). Marcas resilientes possuem alta densidade (significados claros e múltiplos) e baixa vulnerabilidade a ressignificações negativas.',
    findings: ['Índice de Coerência média: 6.2/10', 'Vulnerabilidade em marcas genéricas'],
    recommendations: 'Monitorar a marca por "Nuvens de Significado", não apenas por volume de citações.',
    nextSteps: 'Implementação de monitoramento em tempo real.',
    references: ['Data Semiotics 2026'],
    truthScore: 99.0,
    metrics: [{ label: 'Semantic Density', value: '8.4/10', percentage: 84, trend: 'up' }]
  },
  {
    id: 'B.13',
    cat: 'brand',
    title: '9.13 Desconstrução Semiótica',
    desc: 'Anti-convenção como estratégia.',
    summary: 'Framework ISS (Índice de Subversão Semiótica) e análise de cases disruptivos brasileiros.',
    methodology: 'Deconstrução de Derrida aplicada ao varejo brasileiro (Cases: Toguro, Cimed, Bom Beef).',
    analysis: 'A quebra deliberada de códigos (ex: Mansão Maromba usando PET para álcool premium ou Linha Urso da Cimed usando embalagem de material de construção) gera Dissonância Cognitiva. O estranhamento atrai a atenção orgânica e desancora o preço da categoria tradicional. O ISS Score analisa a distância dos códigos-categoria, a manutenção funcional e o potencial de buzz.',
    findings: [
      'Toguro Case: Inversão popular de códigos premium',
      'Cimed/Urso: Category Transplant (Construção -> Saúde)',
      'Atenção Orgânica gerada: +450% vs categoria'
    ],
    recommendations: 'Subverter um código rígido (Embalagem ou Linguagem) enquanto mantém a clareza do benefício principal.',
    nextSteps: 'Playbook: Auditoria -> Identificação de Rigidez -> Subversão -> Teste Funcional -> Lançamento.',
    references: ['Derrida: Deconstruction', 'Barthes: Mythologies'],
    sources: [{ label: 'Cimed Innovation', url: 'https://cimed.com.br' }],
    truthScore: 99.1,
    metrics: [
      { label: 'ISS Index', value: '9.2/10', percentage: 92, trend: 'up' },
      { label: 'Attention Premium', value: '450%', percentage: 85, trend: 'up' }
    ],
    insightCards: [
      { title: 'Category Transplant', content: 'Trazer signos de construção civil para suplementos cria uma percepção de "força bruta" imediata.' },
      { title: 'Cognitive Dissonance', content: 'O estranhamento gera um registro de memória 10x mais forte.' }
    ]
  },

  // ==========================================
  // 10. CULTURA & ENTRETENIMENTO
  // ==========================================
  {
    id: 'CU.1',
    cat: 'culture',
    title: '10.1 Streaming Wars Brasil 2026',
    desc: 'O colapso da assinatura genérica.',
    summary: 'Análise de Churn e a verticalização do conteúdo nacional em plataformas globais.',
    methodology: 'Telemetria de apps e análise transacional de assinaturas via Drex.',
    analysis: 'O modelo de catálogo infinito morreu por fadiga de escolha. Consumidores buscam "Curadoria Radical". A produção nacional tornou-se o único diferencial de retenção real. 35% de churn em apps sem conteúdo local forte.',
    findings: ['Churn em massa: 35%', 'Valor Conteúdo Nacional: +150%'],
    recommendations: 'Priorizar parcerias com produtoras locais para criação de IPs proprietárias brasileiras.',
    nextSteps: 'Integração de streaming com micro-recompensas gamificadas.',
    references: ['Digital TV Research 2026'],
    truthScore: 94.7,
    metrics: [{ label: 'Local Retention', value: '82%', percentage: 82, trend: 'up' }]
  },
  {
    id: 'CU.2',
    cat: 'culture',
    title: '10.2 Gaming Deep Dive BR',
    desc: 'Mobile como console dominante.',
    summary: 'Democratização do E-sports via smartphone nas periferias brasileiras.',
    methodology: 'Análise de telemetria de dispositivos e volume transacional in-game.',
    analysis: 'O Brasil é um país de smartphones. O crescimento de E-sports mobile superou consoles em 300%. A economia de "Ads Recompensados" gera renda real em comunidades de baixa renda.',
    findings: ['Hegemonia Mobile: 85%', 'Renda in-game média: R$ 1.2k/mês'],
    recommendations: 'Marcas não-endêmicas devem entrar via torneios comunitários, não apenas grandes ligas.',
    nextSteps: 'Lançamento de colecionáveis de marca para jogos mobile de massa.',
    references: ['Newzoo: Global Games Market BR'],
    truthScore: 96.2,
    metrics: [{ label: 'Mobile Hegemony', value: '85%', percentage: 85, trend: 'up' }]
  },

  // ==========================================
  // IA, ALGORITMOS & TECNOLOGIA (RESTAURADOS)
  // ==========================================
  {
    id: 'A.1',
    cat: 'algo',
    title: 'Ontologia da Intenção',
    desc: 'Mapeando o "Porquê" em sistemas.',
    summary: 'Transição de algoritmos de frequência para modelos de significado ontológico profundo.',
    methodology: 'Ontological Engineering aplicada a LLMs e Knowledge Graphs.',
    analysis: 'Em 2026, processar dados não é suficiente; entender a intenção ontológica é o novo fosso competitivo. Redução de 95% em alucinações via RAG Ontológico.',
    findings: ['Redução Alucinação: 95%', 'Eficiência de Contexto: +300%'],
    recommendations: 'Arquitetar schemas de dados baseados em ontologias de domínio reais.',
    nextSteps: 'Migração de taxonomias estáticas para grafos dinâmicos.',
    references: ['Stanford Encyclopedia: Ontological Engineering'],
    truthScore: 99.2,
    metrics: [{ label: 'Semantic Accuracy', value: '98%', percentage: 98, trend: 'up' }]
  },
  {
    id: 'M.1',
    cat: 'market',
    title: 'Sovereign AI: Brasil Hub',
    desc: 'Soberania de dados no Ceará.',
    summary: 'A infraestrutura do Nordeste como porto seguro para IA de baixa latência.',
    methodology: 'Análise de cabos submarinos e investimentos em datacenters via Gartner.',
    analysis: 'O custo da energia renovável no CE tornou o Brasil o hub de IA soberana. Empresas estão migrando para SLMs (Small Language Models) refinadas localmente.',
    findings: ['Adoção Nuvem Soberana: 72%', 'Latência Fortaleza-Lisboa: <15ms'],
    recommendations: 'Priorizar workloads sensíveis em provedores locais com certificação de soberania.',
    nextSteps: 'Auditoria de conectividade submarina para redundância.',
    references: ['Gartner: Strategic Tech 2026'],
    truthScore: 98.4,
    metrics: [{ label: 'Local Adoption', value: '72%', percentage: 72, trend: 'up' }]
  },
  {
    id: 'D.1',
    cat: 'data',
    title: 'Betting Integrity 2026',
    desc: 'Caçando fraudes no futebol.',
    summary: 'Regulação algorítmica e monitoramento via Drex para integridade esportiva.',
    methodology: 'Cruzamento de volumes de apostas e telemetria de campo.',
    analysis: 'O sistema Grito de Alerta detecta anomalias em tempo real. Lavagem de dinheiro no esporte caiu 85% após implementação do Drex.',
    findings: ['Detecção Fraude: 99%', 'Redução Lavagem: 85%'],
    recommendations: 'Operadoras devem integrar APIs federais de monitoramento biométrico.',
    nextSteps: 'Expansão para campeonatos regionais e divisões de base.',
    references: ['Interpol: Betting Integrity'],
    truthScore: 98.7
  },
  {
    id: 'E.1',
    cat: 'esg',
    title: 'Crédito de Carbono 3.0',
    desc: 'Tokenização e liquidez verde.',
    summary: 'Amazônia preservada como ativo financeiro via smart contracts e satélite.',
    methodology: 'Sentinel Satellite Data + Drex Smart Contracts.',
    analysis: 'Preservar é rentável. Smart contracts cancelam rendimentos automaticamente em caso de desmatamento detectado por satélite em tempo real.',
    findings: ['Liquidez Carbono: +400%', 'Acurácia Satélite: 99.8%'],
    recommendations: 'Empresas devem migrar compensações para ativos tokenizados verificáveis.',
    nextSteps: 'Lançamento do Marketplace B3 de Ativos Ambientais.',
    references: ['ESA: Sentinel Protocols'],
    truthScore: 98.7
  },
  {
    id: 'C.1',
    cat: 'consumer',
    title: 'A Morte do Algoritmo Genérico',
    desc: 'O fim dos feeds infinitos.',
    summary: 'Migração para micro-comunidades curadas por humanos em vez de IA pura.',
    methodology: 'Etnografia digital e taxas de churn de plataformas de massa.',
    analysis: 'Fadiga de dopamina gerou o movimento "Oásis Digitais". A conversão em tribos de 5k pessoas é 8x maior que em grandes redes sociais.',
    findings: ['Churn Redes Massa: 25%', 'Conversão Comunidade: 8x'],
    recommendations: 'Investir em infraestrutura própria de comunidade (Discord/Circle) em vez de dependência algorítmica.',
    nextSteps: 'Migração de investimentos de Meta/Google para nichos tribais.',
    references: ['Nielsen: Future of Channels'],
    truthScore: 93.9
  },
  {
    id: 'F.1',
    cat: 'finance',
    title: 'Real Estate Tokenization',
    desc: 'Comprando m² via Drex.',
    summary: 'Democratização do investimento imobiliário através de frações líquidas.',
    methodology: 'Análise do piloto Drex e registros digitais em Blockchain.',
    analysis: 'Liquidez imobiliária explodiu 80%. O Drex permitiu que frações de R$ 100 gerassem aluguel diário automático para o investidor de varejo.',
    findings: ['Liquidez Mercado: +80%', 'Custo Transação: -90%'],
    recommendations: 'Incorporadoras devem tokenizar 100% dos lançamentos para garantir funding imediato.',
    nextSteps: 'Integração de APIs de corretagem com o sistema Drex.',
    references: ['BCB: Drex Pilot Phase 4'],
    truthScore: 98.4
  },
  {
    id: 'MO.1',
    cat: 'mobility',
    title: 'Drones de Entrega SP',
    desc: 'Logística aérea urbana.',
    summary: 'Malha logística que removeu 40% do delivery das ruas engarrafadas.',
    methodology: 'Telemetria de 500k voos autônomos em áreas densas.',
    analysis: 'Drones autônomos entregam pacotes de 2kg em 10min. O custo por entrega caiu 70% comparado a motoboys tradicionais.',
    findings: ['Tempo Entrega: -70%', 'Pegada Carbono Logística: -85%'],
    recommendations: 'Condomínios devem instalar vertiportos para recepção automatizada.',
    nextSteps: 'Regulação de ruído aéreo junto à prefeitura de SP.',
    references: ['ANAC: Drone Delivery Guidelines'],
    truthScore: 94.2
  },
  {
    id: 'H.1',
    cat: 'health',
    title: 'Genômica Popular',
    desc: 'DNA por R$ 100.',
    summary: 'Mapeamento genético integrado ao check-up básico no SUS e rede privada.',
    methodology: 'Sequenciamento de baixo custo e análise preditiva de saúde.',
    analysis: 'O SUS economiza bilhões ao focar na prevenção baseada no DNA. 45% de diagnósticos de câncer agora são feitos antes dos sintomas físicos.',
    findings: ['Custo Sequenciamento: <$20', 'Diagnóstico Precoce: +45%'],
    recommendations: 'Integrar dados genômicos ao prontuário eletrônico unificado nacional.',
    nextSteps: 'Expansão do Plano Nacional de Genética.',
    references: ['Nature Genetics 2026'],
    truthScore: 97.9
  }
];
